# Generated by Django 4.1.7 on 2023-03-07 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_remove_game_attendees_game_attendees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='players_at_game',
        ),
    ]
