# Generated by Django 4.1.7 on 2023-03-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_game_attendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='lat',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='lng',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
